In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat =[ [1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr=np.arange(0,10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# eye to get identity matrice

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# to generate random numbers

In [16]:
np.random.rand(5)

array([0.85277164, 0.23261878, 0.1353881 , 0.30947291, 0.20267268])

In [17]:
np.random.rand(5,5)

array([[0.54661973, 0.8560852 , 0.24664579, 0.94964506, 0.28586316],
       [0.15547508, 0.57934921, 0.51883003, 0.39140962, 0.87007874],
       [0.32751416, 0.07902479, 0.70022136, 0.60756805, 0.62423744],
       [0.34799742, 0.14447378, 0.80365391, 0.43666449, 0.32798003],
       [0.6281402 , 0.87817713, 0.18542382, 0.45670101, 0.02286299]])

In [19]:
np.random.randn(2)

array([ 1.78802655, -0.2134893 ])

In [20]:
np.random.randn(5,5)

array([[-0.30677368, -1.03029452,  0.58241601, -0.94027128, -0.31456764],
       [ 0.89864189,  0.1805176 , -0.93872673,  0.53420397,  0.81979379],
       [-0.93440148,  1.5633828 , -0.03418658,  0.20774879, -1.36353917],
       [-1.23365657, -2.04888577,  0.11636938,  0.1845179 ,  0.20300613],
       [-0.51440907, -0.01430963,  2.13787683, -0.76516696, -0.71422129]])

to get a random integer

In [21]:
np.random.randint(1,100)

91

In [23]:
np.random.randint(1,100,5)

array([38, 34, 16, 89, 56])

In [24]:
ranarr = np.random.randint(1,50,10)

In [27]:
ranarr.reshape(2,5)

array([[ 9, 23, 46, 24, 37],
       [32, 31, 49, 33, 40]])

to find max and min values

In [28]:
ranarr.max()

49

In [29]:
ranarr.min()

9

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.argmin()

0

In [33]:
ranarr.shape

(10,)

In [36]:
arr = ranarr. reshape(2,5)

In [37]:
arr.dtype

dtype('int32')

In [40]:
from numpy.random import randint

In [45]:
randint(2,100)

22